img_size:
  h: 48
# Small font_size will make text looks like blured/prydown
font_size:
  min: 42
  max: 44
# choose Text color range
# color boundary is in R,G,B format
font_color:
  enable: true
  blue:
    fraction: 0.2
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]
  brown:
    fraction: 0.15
    l_boundary: [139,70,19]
    h_boundary: [160,82,43]
  black:
    fraction: 0.25
    l_boundary: [0,0,0]
    h_boundary: [10,10,10]
  red:
    fraction: 0.2
    l_boundary: [200,0,0]
    h_boundary: [250,10,10]
  yellow:
    fraction: 0.2
    l_boundary: [200, 200, 0]
    h_boundary: [225, 225, 50]

# By default, text is drawed by Pillow with (https://stackoverflow.com/questions/43828955/measuring-width-of-text-python-pil)
# If `random_space` is enabled, some text will be drawed char by char with a random space
random_space:
  enable: false
  fraction: 0.5
  min: 0 # -0.1 will make chars very close or even overlapped
  max: 0.4

random_direction:
  enable: true
  fraction: 0.5


# Do remap with sin()
# Currently this process is very slow!
curve:
  enable: true
  fraction: 0.3
  period: 360  # degree, sin 函数的周期
  min: 1 # sin 函数的幅值范围
  max: 5

# random crop text height
crop:
  enable: False
  fraction: 0.3

  # top and bottom will applied equally
  top:
    min: 5
    max: 10 # in pixel, this value should small than img_height
  bottom:
    min: 5
    max: 10 # in pixel, this value should small than img_height

# Use image in bg_dir as background for text
img_bg:
  enable: true
  fraction: 0.7

# Not work when random_space applied
text_border:
  enable: true
  fraction: 0.5

  # lighter than word color
  light:
    enable: true
    fraction: 0.5

  # darker than word color
  dark:
    enable: true
    fraction: 0.5

# https://docs.opencv.org/3.4/df/da0/group__photo__clone.html#ga2bf426e4c93a6b1f21705513dfeca49d
# https://www.cs.virginia.edu/~connelly/class/2014/comp_photo/proj2/poisson.pdf
# Use opencv seamlessClone() to draw text on background
# For some background image, this will make text image looks more real
seamless_clone:
  enable: true
  fraction: 0.5

perspective_transform:
  max_x: 30
  max_y: 30
  max_z: 4

blur:
  enable: true
  fraction: 0.05

# If an image is applied blur, it will not be applied prydown
prydown:
  enable: false
  fraction: 0.05
  max_scale: 1.5 # Image will first resize to 1.5x, and than resize to 1x

noise:
  enable: true
  fraction: 0.3

  gauss:
    enable: true
    fraction: 0.35

  uniform:
    enable: true
    fraction: 0.35

  salt_pepper:
    enable: false
    fraction: 0.25

  poisson:
    enable: true
    fraction: 0.30

line:
  enable: true
  fraction: 0.1

  under_line:
    enable: true
    fraction: 0.3

  table_line:
    enable: true
    fraction: 0.3

  middle_line:
    enable: true
    fraction: 0.4

line_color:
  enable: true
  black:
    fraction: 0.4
    l_boundary: [0,0,0]
    h_boundary: [64,64,64]
  blue:
    fraction: 0.2
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]
  white:
    fraction: 0.4
    l_boundary: [254,254,254]
    h_boundary: [255,255,255]

# These operates are applied on the final output image,
# so actually it can also be applied in training process as an data augmentation method.

# By default, text is darker than background.
# If `reverse_color` is enabled, some images will have dark background and light text
reverse_color:
  enable: true
  fraction: 0.1

emboss:
  enable: false
  fraction: 0.05

sharp:
  enable: false
  fraction: 0.1
