ENV:
  output_dir: output
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_output: True
  return_res: True
  print_res: True

MODEL:
  - ClassificationOp:
      name: cls
      param_path: https://paddleclas.bj.bcebos.com/models/PULC/inference/image_orientation_infer/inference.pdiparams
      model_path: https://paddleclas.bj.bcebos.com/models/PULC/inference/image_orientation_infer/inference.pdmodel
      batch_size: 8
      last_ops:
        - input
      PreProcess:
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
            channel_num: 3
        - ToCHWImage:
        - ExpandDim:
            axis: 0
      PostProcess:
        - ThreshOutput:
            threshold: 0
            class_id_map_file: deploy/utils/label_map/image_orientation_label_list.txt
      Inputs:
        - image

  - ClasOutput:
      name: vis
      last_ops:
        - input
        - cls
      Inputs:
        - fn
        - image
        - class_ids
        - scores
        - label_names
