ENV:
  run_mode: paddle
  device: GPU
  min_subgraph_size: 3
  shape_info_filename: ./
  trt_calib_mode: False
  cpu_threads: 1
  trt_use_static: False
  save_img: False
  save_res: False
  return_res: true


MODEL:
  - OcrCrnnRecOp:
      name: rec
      param_path: paddlecv://models/ch_PP-OCRv3_rec_infer/inference.pdiparams
      model_path: paddlecv://models/ch_PP-OCRv3_rec_infer/inference.pdmodel
      batch_size: 6
      last_ops:
        - input
      PreProcess:
        - ReisizeNormImg:
            rec_image_shape: [3, 48, 320]
      PostProcess:
        - CTCLabelDecode:
            character_dict_path: "paddlecv://dict/ocr/ch_dict.txt"
            use_space_char: true
      Inputs:
        - image

  - OCRRecOutput:
      name: vis
      last_ops:
        - input
        - rec
      Inputs:
        - fn
        - image
        - rec_text
        - rec_score
